### ISSUE TITLE
hey, cool project :)

### ISSUE THREAD

**Issue by nornagon** [axle-h/baby-smash#1]
this isn't an issue, but i just wanted to say i stumbled across this looking at who's using flatten-svg, and i'm so glad you made this fun thing with it! i just had a baby daughter of my own and i'm very excited for her to start, er, "assisting" me working from home :joy: what a beautiful photo of you two!

**Comment by axle-h** [comment]
Hey, just spotted this! Thanks for reaching out. Love this - exactly what open source software is about!
